# Generated by Django 5.0.6 on 2024-06-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0002_alter_appointment_notes_alter_branch_office_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
