# Generated by Django 5.0.6 on 2024-06-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0003_alter_doctor_phone_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_office',
            name='address',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch_office',
            name='name',
            field=models.CharField(default='1', max_length=100, unique=True, verbose_name='Branch_office'),
        ),
        migrations.AlterField(
            model_name='branch_office',
            name='phone',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(default='Medicina General', max_length=100, null=True, unique=True),
        ),
    ]
