# Generated by Django 5.0.6 on 2024-06-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0004_alter_branch_office_address_alter_branch_office_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_office',
            name='address',
            field=models.CharField(blank=True, default='1', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='branch_office',
            name='name',
            field=models.CharField(default='1', max_length=240, unique=True, verbose_name='Branch_office'),
        ),
        migrations.AlterField(
            model_name='branch_office',
            name='phone',
            field=models.CharField(blank=True, default='1', max_length=240, null=True),
        ),
    ]
